# Generated by Django 3.2.3 on 2021-06-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_proveedor_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='Ninguna', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido_indiv',
            name='costo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='caracteristicas',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo_unitario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='celular',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_de_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
