# Generated by Django 3.2.3 on 2021-06-10 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20210609_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
