# Generated by Django 3.2.3 on 2021-06-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_carrito_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='costo',
            field=models.FloatField(),
        ),
    ]
